name: "Validate Gradle Wrapper"
on:
  workflow_dispatch: {}
  push:
    paths:
      - 'gradle/wrapper/gradle-wrapper.jar'
      - 'gradle/wrapper/gradle-wrapper.properties'
  pull_request:
    paths:
      - 'gradle/wrapper/gradle-wrapper.jar'
      - 'gradle/wrapper/gradle-wrapper.properties'

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
